"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { getWorkspace } from "../../../lib/case-service";
import type { CaseWorkspaceState } from "../../../lib/types";

export default function ReportPage() {
  const { caseId } = useParams<{ caseId: string }>();
  const [workspace, setWorkspace] = useState<CaseWorkspaceState | null>(null);
  useEffect(() => { getWorkspace(caseId).then(setWorkspace).catch(() => setWorkspace(null)); }, [caseId]);
  if (!workspace) return <main className="p-8">Loading report…</main>;
  const guidance = workspace.guidance;
  return <main className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><article className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="flex items-start justify-between gap-4"><div><Link href={`/cases/${encodeURIComponent(caseId)}`} className="text-sm font-bold text-blue-700">← Case workspace</Link><h1 className="mt-5 text-3xl font-black">Investigation Report</h1><p className="mt-1 text-sm text-slate-500">{workspace.title} · revision {workspace.caseRevision}</p></div>{guidance?.assessment_is_stale && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Assessment out of date</span>}</div><section className="mt-8"><h2 className="text-xl font-black">Case and context</h2><p className="mt-2 text-sm leading-6 text-slate-700">{workspace.assessmentContext?.title ?? "No assessment context has been recorded."}</p></section><section className="mt-8"><h2 className="text-xl font-black">Per-subject findings</h2>{guidance?.per_subject_assessments?.length ? <div className="mt-4 space-y-6">{guidance.per_subject_assessments.map((assessment) => <section key={assessment.subject_id} className="border-t border-slate-200 pt-4"><h3 className="font-bold">{assessment.subject_id}</h3>{assessment.violation_assessments.map((item) => <div key={item.violation_id} className="mt-3 rounded-lg bg-slate-50 p-4"><div className="flex justify-between gap-3"><strong>{item.violation_id}</strong><span className="text-xs font-bold uppercase">{item.status}</span></div><p className="mt-2 text-sm leading-6">{item.reasoning_summary}</p><p className="mt-2 text-xs text-slate-500">Supporting: {item.supporting_node_ids.join(", ") || "None"} · Mitigating: {item.mitigating_node_ids.join(", ") || "None"}</p></div>)}<p className="mt-4 text-sm font-semibold">Furthest justified conclusion: {assessment.furthest_conclusion.statement}</p></section>)}</div> : <p className="mt-3 text-sm text-slate-600">No successful assessment is available yet.</p>}</section><section className="mt-8"><h2 className="text-xl font-black">Sources</h2><ul className="mt-3 space-y-2 text-sm">{workspace.visibleSources.map((source) => <li key={source.id}><strong>{source.id} — {source.name}</strong> · {source.sourceType}</li>)}</ul></section><p className="mt-10 border-t border-slate-200 pt-5 text-sm leading-6 text-slate-600">This report supports institutional investigation and does not constitute the final disciplinary judgment. NOT_CURRENTLY_SUPPORTED does not mean innocence established.</p></article></main>;
}
