"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { getReport } from "../../../lib/case-service";
import type { ReportResponse } from "../../../lib/types";

export default function ReportPage() {
  const { caseId } = useParams<{ caseId: string }>();
  const [report, setReport] = useState<ReportResponse | null>(null);
  useEffect(() => { getReport(caseId).then(setReport).catch(() => setReport(null)); }, [caseId]);
  if (!report) return <main className="p-8">Loading report…</main>;
  return <main className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><article className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><Link href={`/cases/${encodeURIComponent(caseId)}`} className="text-sm font-bold text-blue-700">← Case workspace</Link><div className="mt-5 flex items-start justify-between gap-4"><div><h1 className="text-3xl font-black">Investigation Report</h1><p className="mt-1 text-sm text-slate-500">{report.title}</p></div>{report.assessmentIsStale && <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Assessment out of date</span>}</div>{report.reportState === "unavailable" ? <p className="mt-8 text-sm text-slate-600">No successful assessment is available yet.</p> : <section className="mt-8"><h2 className="text-xl font-black">Findings by student</h2><div className="mt-4 space-y-6">{report.students.map((student) => <section key={student.displayName} className="border-t border-slate-200 pt-4"><h3 className="font-bold">{student.displayName}</h3>{student.violations.map((item) => <div key={item.label} className="mt-3 rounded-lg bg-slate-50 p-4"><div className="flex justify-between gap-3"><strong>{item.label}</strong><span className="text-xs font-bold uppercase">{item.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-sm leading-6">{item.reasoningSummary}</p><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><strong>Supporting material</strong><ul className="mt-1 list-disc pl-5">{item.supportingMaterial.length ? item.supportingMaterial.map((material, index) => <li key={`${material.statement}-${index}`}>{material.sourceLabels.length ? `${material.sourceLabels.join(", ")} — ` : ""}{material.statement}</li>) : <li>None recorded.</li>}</ul></div><div><strong>Limiting material</strong><ul className="mt-1 list-disc pl-5">{item.limitingMaterial.length ? item.limitingMaterial.map((material, index) => <li key={`${material.statement}-${index}`}>{material.sourceLabels.length ? `${material.sourceLabels.join(", ")} — ` : ""}{material.statement}</li>) : <li>None recorded.</li>}</ul></div></div></div>)}<p className="mt-4 text-sm font-semibold">Furthest justified conclusion: {student.furthestConclusion}</p></section>)}</div></section>}<p className="mt-10 border-t border-slate-200 pt-5 text-sm leading-6 text-slate-600">This report supports institutional investigation and does not constitute the final disciplinary judgment.</p></article></main>;
}
