from collections.abc import Sequence
from pathlib import Path
from typing import Any, Protocol

from investigator.state import CaseState


class InvestigationEnvironment(Protocol):
    @property
    def environment_id(self) -> str: ...

    @property
    def case_id(self) -> str: ...

    def initial_case_input(self) -> str: ...
    def initial_prompt(self) -> str: ...
    def assessment_context(self) -> str: ...
    def build_initial_state(self, response: Any) -> CaseState: ...
    def available_actions(self, completed_action_ids: set[str]) -> Sequence[Any]: ...
    def get_action(self, action_id: str) -> Any: ...
    def execute_action(self, state: CaseState, action_id: str) -> Any: ...
    def revision_prompt(self, session: Any, release: Any) -> str: ...
    def next_action_prompt(self, session: Any, available_actions: Sequence[Any]) -> str: ...


def project_root_from(path: str | Path) -> Path:
    """Resolve an explicit project root from an application or runner file."""
    return Path(path).resolve().parents[1]
