import json

from investigator.cycle import InvestigatorObservation, TURN_RESPONSE_ADAPTER
from investigator.roles.procedure import render_procedure


def build_investigator_cycle_prompt(observation: InvestigatorObservation) -> str:
    """Render the bounded local Investigator contract from its live Pydantic schema."""
    local_graph = observation.local_graph.model_dump(mode="json")
    enquiries = [item.model_dump(mode="json") for item in observation.available_enquiries]
    schema = TURN_RESPONSE_ADAPTER.json_schema()
    sources = "\n\n".join(
        f'<SOURCE source_id="{source.id}" filename="{source.name}">\n{source.content or ""}\n</SOURCE>'
        for source in observation.visible_sources
    )
    return "\n\n".join([
        "<ROLE>\nYou are the local Investigator, not the global Case Steward or final judge. Work from the currently visible case context.\n</ROLE>",
        "<EVIDENCE_DISCIPLINE>\nA claim is not a fact. A source statement establishes that the statement was made, not automatically that it is true. Knowledge is not misconduct; opportunity is not use; association is not prohibited collaboration; credential or device use does not confirm the person; anomaly is not misconduct; contradiction is not automatically deception or intent; absence of evidence is not evidence of absence. Distinguish raw SOURCE, semantic EVIDENCE, PROPOSITION, HYPOTHESIS, and UNCERTAINTY.\n</EVIDENCE_DISCIPLINE>",
        "<INVESTIGATOR_GLOSSARY>\nSOURCE is an original case record outside the semantic graph. EVIDENCE is a direct observation grounded in readable SOURCEs. PROPOSITION is a smaller truth-apt inference from EVIDENCE/PROPOSITION. HYPOTHESIS is a broader explanation. UNCERTAINTY is a consequential unresolved question. These namespaces preserve provenance and prevent a record, inference, or question from being confused with truth.\n</INVESTIGATOR_GLOSSARY>",
        "<INVESTIGATOR_PROCEDURE>\n" + render_procedure("investigator") + "\n</INVESTIGATOR_PROCEDURE>",
        "<OPERATION_POLICY>\nIF a directly source-grounded graph operation is offered by the exact schema, use the relevant visible source reference and verify the observation against that source.\nELIF a statement is a small inference from visible graph material, use ADD_PROPOSITION with appropriate derivation or relation.\nELIF a statement is a broader explanation, reuse a substantively equivalent HYPOTHESIS; otherwise create one using the exact schema branch.\nELIF a consequential question remains unresolved, use ADD_UNCERTAINTY.\nIF precise target uncertainty and usefulness are justified, use REQUEST_EVIDENCE with every required field. ELIF useful context is missing but that specificity has not been earned, use REQUEST_OPEN with reason and optional information_sought. ELIF predefined actions are explicitly offered, use only a listed legacy REQUEST_ENQUIRY; ELSE PASS.\nIF a request returns ALREADY_AVAILABLE or NO_NEW_SOURCE: review current visible sources, continue from what they support, and do not immediately repeat the same request.\nIF a request is UNAVAILABLE: NEVER infer the requested proposition is false; reassess another useful enquiry, local reasoning, or Steward review.\nMOVE_FOCUS may target only a legal canonical graph node in the active local view. ELSE NEVER reference or focus it.\nNEVER create a Steward operation, release a raw source, decide guilt, or use a hidden source or mechanism.\n</OPERATION_POLICY>",
        "<LOCAL_AUTHORITY>\nThe exact runtime Pydantic schema defines which graph operations are available. The coordinator defines mechanical legality. active_reasoning_node_ids are the legal visible graph-node set; Raw SourceRegistry visibility is a separate namespace from semantic graph locality, and a visible raw source is not inaccessible merely because there is no semantic graph node for it.\n</LOCAL_AUTHORITY>",
        "<CYCLE_DISCIPLINE>\nAll graph_updates form one coherent local step and are applied in order. Reason first, operation second; prerequisites must be satisfied before serialization. CONTINUE_LOCAL requires graph work. REQUEST_STEWARD_REVIEW requests global case management without selecting the Steward operation.\n</CYCLE_DISCIPLINE>",
        "<HUMAN_EVIDENCE_REQUESTS>\nRequest an information need rather than a prescribed artefact or collection mechanism. Prefer the least specific useful request; do not assume hidden sources exist, expose hidden inventory, or prescribe invasive or impossible collection.\n</HUMAN_EVIDENCE_REQUESTS>",
        f"<CASE_SOURCES>\n{sources}\n</CASE_SOURCES>",
        f"<CURRENT_OBSERVATION>\n{json.dumps({'current_focus': observation.current_focus.model_dump(mode='json'), 'local_graph': local_graph, 'available_enquiries': enquiries, 'participants': observation.participants, 'tenure_turn_count': observation.tenure_turn_count, 'max_turns_per_tenure': observation.max_turns_per_tenure, 'turns_remaining': observation.turns_remaining, 'in_flight_enquiry': observation.in_flight_enquiry.model_dump(mode='json') if observation.in_flight_enquiry else None, 'recently_released_evidence_ids': observation.recently_released_evidence_ids, 'workflow_feedback': observation.workflow_feedback}, sort_keys=True)}\n</CURRENT_OBSERVATION>",
        "<OUTPUT_SCHEMA>\nReturn exactly one JSON object validated as InvestigatorTurnResponse. The following schema is generated directly from the production Pydantic contract; use its exact field names, discriminator values, and branch shapes. Do not add commentary, markdown fences, graph metadata, or fields outside the schema.\n" + json.dumps(schema, indent=2, sort_keys=True) + "\n</OUTPUT_SCHEMA>",
    ])
